[colors.normal]
black = "0x000000"
blue = "0xBAD7FF"
cyan = "0x88AfA2"
green = "0x90A959"
magenta = "0xAA759F"
red = "0xB46958"
white = "0xE1E1E1"
yellow = "0xF4BF75"

[colors.primary]
background = "0x151515"
foreground = "0xE1E1E1"
